version: '3'
services:
  mysql:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    container_name: com.carRent
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carRent